# config package
from .ai_config import (
    KOREAN_LANGUAGE_INSTRUCTION,
    OPENAI_MODEL_COMPLETION_LIMITS,
    DEFAULT_OPENAI_COMPLETION_LIMIT
)

__all__ = [
    'KOREAN_LANGUAGE_INSTRUCTION',
    'OPENAI_MODEL_COMPLETION_LIMITS',
    'DEFAULT_OPENAI_COMPLETION_LIMIT',
]

